FROM cypress/included:12.17.0

ENV QT_X11_NO_MITSHM=1 \
    _X11_NO_MITSHM=1 \
    _MITSHM=0 \
    CYPRESS_CACHE_FOLDER=/home/node/.cache/Cypress

WORKDIR /app
COPY . .

# Installer les dépendances nécessaires pour la validation DB
RUN npm install pg 
RUN npx cypress install --force \
    && mkdir -p /home/node/.cache/Cypress \
    && chown -R node:node /home/node/.cache
USER node

CMD ["npx", "cypress", "run", "--headless", "--config", "video=false,screenshotOnRunFailure=false"]
