image: docker:24.0.9

services:
  - name: docker:24.0.9-dind
    alias: docker

variables:
  DOCKER_HOST: tcp://localhost:2375  
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2

before_script:
  
  - echo "Waiting for Docker daemon to be ready..."
  - timeout 30 sh -c 'until docker info; do sleep 1; done' || false\
  - ps aux
  - netstat -tlnp
  - docker version
  - docker compose version


stages:
  - test

test_e2e:
  stage: test
  script:
    - docker compose -f docker-compose.ci.yaml up -d --scale cypress=0
    - docker compose -f docker-compose.ci.yaml run --rm cypress npx cypress run
    - EXIT_CODE=$?
    - docker compose -f docker-compose.ci.yaml down
    - exit $EXIT_CODE