image: docker:24.0.9-cli

variables:
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://localhost:2375

before_script:
  - apk add --no-cache docker docker-cli-compose
  - dockerd --host=tcp://0.0.0.0:2375 --storage-driver=overlay2 &  
  - timeout 20 sh -c 'until docker info; do sleep 1; done'
  - docker version
  - docker compose version


stages:
  - test

test_e2e:
  stage: test
  script:
    - docker compose -f docker-compose.ci.yaml up -d --scale cypress=0
    - docker compose -f docker-compose.ci.yaml run --rm cypress npx cypress run
    - EXIT_CODE=$?
    - docker compose -f docker-compose.ci.yaml down
    - exit $EXIT_CODE