image: ubuntu:22.04

variables:
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://localhost:2375

before_script:
  - apt-get update -y
  - apt-get install -y docker.io docker-compose net-tools
  - dockerd --host=tcp://0.0.0.0:2375 --storage-driver=overlay2 > /dev/null 2>&1 &
  - sleep 10
  - ps aux | grep dockerd
  - netstat -tlnp
  - docker info
  - docker compose version


stages:
  - test

test_e2e:
  stage: test
  script:
    - docker compose -f docker-compose.ci.yaml up -d --scale cypress=0
    - docker compose -f docker-compose.ci.yaml run --rm cypress npx cypress run
    - EXIT_CODE=$?
    - docker compose -f docker-compose.ci.yaml down
    - exit $EXIT_CODE