image: docker:latest
services:
  - name: docker:dind
    command: ["--tls=false"]
 
variables:
  DOCKER_TLS_CERTDIR: "/certs"  # Enable TLS (default)
  DOCKER_DRIVER: overlay2


stages:
  - test

test_e2e:
  stage: test
  script:
    - docker compose -f docker-compose.ci.yaml up -d --scale cypress=0
    - docker compose -f docker-compose.ci.yaml run --rm cypress npx cypress run
    - EXIT_CODE=$?
    - docker compose -f docker-compose.ci.yaml down
    - exit $EXIT_CODE