image: docker:24.0.9-cli

variables:
  DOCKER_HOST: tcp://localhost:2375
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2

before_script:
  # Installer les dépendances nécessaires
  - apk add --no-cache shadow docker-cli-buildx
  # Configurer les permissions Docker
  - mkdir -p /etc/docker
  - echo '{"storage-driver":"overlay2"}' > /etc/docker/daemon.json
  # Démarrer le daemon Docker en mode debug
  - dockerd --host=tcp://0.0.0.0:2375 > /tmp/dockerd.log 2>&1 &
  # Attendre que Docker soit prêt avec timeout
  - |
    echo "Attente du démarrage de Docker..."
    for i in $(seq 1 30); do
      if docker info >/dev/null 2>&1; then
        echo "Docker démarré avec succès"
        break
      fi
      sleep 1
      echo "Attente... (${i}/30)"
      # Afficher les logs si échec
      if [ $i -eq 30 ]; then
        echo "Échec du démarrage de Docker - derniers logs:"
        tail -n 50 /tmp/dockerd.log
        exit 1
      fi
    done
  # Vérifier les versions
  - docker version
  - docker compose version


stages:
  - test

test_e2e:
  stage: test
  script:
    - docker compose -f docker-compose.ci.yaml up -d --scale cypress=0
    - docker compose -f docker-compose.ci.yaml run --rm cypress npx cypress run
    - EXIT_CODE=$?
    - docker compose -f docker-compose.ci.yaml down
    - exit $EXIT_CODE