apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: app

  labels:
    app: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: djgitdev/notificationservice:latest
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"
