apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: ${DOCKER_USER}/orderservice:latest
          ports:
            - containerPort: 8084
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "test"
