apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - name: payment
          image: ${DOCKER_USER}/paymentservice:latest
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "test"
