apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-userinterface
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp-userinterface
  template:
    metadata:
      labels:
        app: webapp-userinterface
    spec:
      containers:
        - name: webapp-userinterface
          image: djgitdev/webapp_userinterface:latest
          ports:
            - containerPort: 5173
          env:
            - name: VITE_API_SERVICE_ORCHESTRE_URL_INTERNAL_NETWORK
              value: "http://orchestre:8080/api/workflow/orchestrate"
            - name: VITE_API_SERVICE_ORCHESTRE_URL_FROM_PROXY
              value: "http://caddy:80/api/workflow/orchestrate"
