apiVersion: v1
kind: Service
metadata:
  name: webapp-userinterface
  namespace: app
spec:
  selector:
    app: webapp-userinterface
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 5173
  type: ClusterIP
