apiVersion: v1
kind: Service
metadata:
  name: caddy
  namespace: app
spec:
  selector:
    app: caddy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort
