name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:

jobs:
  test_e2e:
    runs-on: ubuntu-22.04
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
          

      - name: Start services
        run: |
          docker compose -f docker-compose.ci.yaml up -d --scale cypress=0

      - name: Run Cypress tests
        run: |
          docker compose -f docker-compose.ci.yaml run --rm cypress npm install -g cypress
          docker compose -f docker-compose.ci.yaml run --rm cypress npx cypress install
          docker compose -f docker-compose.ci.yaml run --rm cypress npx cypress run
        continue-on-error: false

      - name: Stop services
        if: always()
        run: docker compose -f docker-compose.ci.yaml down
